#!/bin/bash

(cd ./Resources/anotherUser/ ; git status > ./../../anotherGitStatus.txt; git config user.name > ./../../anotherUserGitCredentials.txt; git config user.email >> ./../../anotherUserGitCredentials.txt)

git status > gitStatus.txt

git config user.name > gitCredentials.txt 

git config user.email >> gitCredentials.txt

javac Main.java 

java Main

#cleanup
rm *.class
rm *.txt
