#!/bin/bash

(cd ./Resources/anotherUser/ ; git status > ./../../anotherGitStatus.txt; git config user.name > ./../../anotherUserGitCredentials.txt; git config user.email >> ./../../anotherUserGitCredentials.txt)

(cd ./Resources/Source\ A/ ; git status) > gitStatus.txt

git config user.name > gitCredentials.txt 

git config user.email >> gitCredentials.txt

javac -cp .:./jaf-1.1.1/activation.jar:./javamail-1.2/mail.jar Main.java 

java -cp .:./jaf-1.1.1/activation.jar:./javamail-1.2/mail.jar Main

#cleanup
rm *.class
rm *.txt
